server:
  port: 8081
  application:
   name: spring-boot-consul-demo

spring:
  http:
    encoding:
      charset: utf-8
      enabled: true
  cloud:
    consul:
#      host: 127.0.0.1
      host: 127.0.0.1
      port: 8500
      discovery:
        enabled: true
        service-name: ${server.application.name}
        instance-id: ${server.application.name}
        health-check-interval: 10s
        register: true
        tags: foo=bar, baz
        health-check-path: /hellospringboot/index
        hostname: 10.252.21.176


env:
  envmaps: 
    env1: h
    env2: z
    env3: w
    env-a: ${env-a} #获取环境变量env-a
    
    